SPK_NAME = make
SPK_VERS = 4.3
SPK_REV = 2
SPK_ICON = src/gnu-make.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = For simple automation, usually of software builds.
RELOAD_UI = no
STARTABLE = no
DISPLAY_NAME = GNU Make
CHANGELOG = "Initial cross-compile."

HOMEPAGE = https://www.gnu.org/software/make/
LICENSE  = GPLv3

include ../../mk/spksrc.spk.mk
